# Generated by Django 5.0.7 on 2024-08-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Contacts',
        ),
    ]
